name: ml_pipeline
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake>=5.2.2
    - python>=3.6.5
    - pyyaml>=3.13
    - pandas>=0.23.4
    - xgboost>=0.72.1
    - joblib>=0.12.2
    - pyarrow>=0.9.0
    - numpy>=1.15.0
    - rpy2>=2.9.1
    - scikit-learn>=0.19.1
    - matplotlib>=2.2.3
