name: ml_pipeline
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake>=5.2.2
    - python>=3.6.5
    - pyyaml>=3.12
    - pandas>=0.23.0
    - xgboost>=0.72.1
    - joblib>=0.12.1
    - pyarrow>=0.10.0
    - numpy>=1.14.3
    - rpy2>=2.9.1
    - scikit-learn>=0.19.1
    - matplotlib>=2.2.2
